import PageHeader from '@/components/shell/page-header';
import Panel from '@/components/ui/panel';
import EmptyValue from '@/components/ui/empty-value';
import Badge from '@/components/ui/badge';
import KpiCard from '@/components/ui/kpi-card';
import { requireAdmin } from '@/lib/auth';
import { createSupabaseServerClient } from '@/lib/supabase/server';
export const dynamic = 'force-dynamic';
type ForecastSetting = { data_start: string | null; data_end: string | null; train_start: string | null; train_end: string | null; test_start: string | null; test_end: string | null; granularity: string; train_row_count: number; test_row_count: number; train_window_ok: boolean; test_window_ok: boolean; isolation_ok: boolean; policy_values: Array<{ config_key: string; numeric_value: number | null; text_value: string | null; boolean_value: boolean | null; description: string | null }> };
function DateValue({ value }: { value: string | null }) { return value ? value : <EmptyValue reason="NOT_CONFIGURED" />; }
export default async function ForecastSettingsPage() { await requireAdmin(); const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.schema('analytics').from('v_forecast_setting').select('*').maybeSingle(); const setting = data as ForecastSetting | null; return <section className="analysis-page"><PageHeader eyebrow="ADMIN / FORECAST" title="Forecast 설정 검증" description="학습·검증 기간과 정책값을 확인합니다. 실제 변경 기능은 다음 단계에서 연결합니다." />{error ? <Panel><p className="auth-error">설정 조회에 실패했습니다: {error.message}</p></Panel> : !setting ? <Panel><p className="empty-state">Forecast 설정이 없습니다. core.forecast_setting migration을 적용하세요.</p></Panel> : <><div className="kpi-grid"><KpiCard label="전체 데이터" value={<>{<DateValue value={setting.data_start} />} ~ {<DateValue value={setting.data_end} />}</>} foot="전체 사용 이력 기준" /><KpiCard label="학습 데이터" value={setting.train_row_count} foot={`${setting.train_window_ok ? '기간 정상' : '기간 확인 필요'}`} tone={setting.train_window_ok ? 'safe' : 'warning'} /><KpiCard label="검증 데이터" value={setting.test_row_count} foot={`${setting.test_window_ok ? '기간 정상' : '기간 확인 필요'}`} tone={setting.test_window_ok ? 'safe' : 'warning'} /><KpiCard label="격리 상태" value={<Badge status={setting.isolation_ok ? 'SAFE' : 'CRITICAL'} />} foot={`Granularity: ${setting.granularity}`} tone={setting.isolation_ok ? 'safe' : 'critical'} /></div><Panel title="기간 설정"><dl className="settings-grid"><div><dt>학습 시작</dt><dd><DateValue value={setting.train_start} /></dd></div><div><dt>학습 종료</dt><dd><DateValue value={setting.train_end} /></dd></div><div><dt>검증 시작</dt><dd><DateValue value={setting.test_start} /></dd></div><div><dt>검증 종료</dt><dd><DateValue value={setting.test_end} /></dd></div><div><dt>Granularity</dt><dd>{setting.granularity}</dd></div></dl></Panel><Panel title="정책값" meta={`${setting.policy_values.length}개`}><div className="data-table-wrap"><table className="data-table"><thead><tr><th>정책 키</th><th>값</th><th>설명</th></tr></thead><tbody>{setting.policy_values.map((policy) => <tr key={policy.config_key}><td>{policy.config_key}</td><td>{policy.numeric_value ?? policy.text_value ?? (policy.boolean_value === null ? '—' : String(policy.boolean_value))}</td><td>{policy.description || '—'}</td></tr>)}</tbody></table></div></Panel></>}</section>; }