'use client';
import { useMemo, useState } from 'react';
import EmptyValue from '@/components/ui/empty-value';
import DataTable, { type Column } from '@/components/analysis/data-table';
import ForecastOverlayChart from '@/components/chart/forecast-overlay-chart';
import type { BacktestChartPoint, BacktestDetail, BacktestPerformance } from '@/lib/backtest/types';

type Run = { backtest_run_id: string; forecast_run_id: string; test_start: string; test_end: string };
type Champion = { backtest_run_id: string; item_id: string; champion_model_id: string };

export default function ComparisonView({ performances, details, runs, champions }: { performances: BacktestPerformance[]; details: BacktestDetail[]; runs: Run[]; champions: Champion[] }) {
  const [item, setItem] = useState(''); const [run, setRun] = useState(runs[0]?.backtest_run_id ?? ''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [selected, setSelected] = useState<string[]>([]);
  const runValue = run || runs[0]?.backtest_run_id; const runData = runs.find((value) => value.backtest_run_id === runValue); const models = useMemo(() => Array.from(new Set(performances.filter((value) => !runValue || value.backtestRunId === runValue).map((value) => value.modelId))), [performances, runValue]); const items = Array.from(new Set(performances.filter((value) => !runValue || value.backtestRunId === runValue).map((value) => value.itemId))); const activeModels = selected.length ? selected : models;
  const rows = performances.filter((value) => (!runValue || value.backtestRunId === runValue) && (!item || value.itemId === item)); const chartRows = details.filter((value) => (!runValue || value.backtestRunId === runValue) && (!item || value.itemId === item) && (!from || value.period >= from) && (!to || value.period <= to)); const points: BacktestChartPoint[] = Array.from(new Set(chartRows.map((value) => value.period))).sort().map((period) => { const periodRows = chartRows.filter((value) => value.period === period); return { period, actual: periodRows.find((value) => value.actual !== null)?.actual ?? null, forecasts: Object.fromEntries(activeModels.map((id) => [id, periodRows.find((value) => value.modelId === id)?.p50 ?? null])), intervals: Object.fromEntries(activeModels.map((id) => { const value = periodRows.find((row) => row.modelId === id); return [id, { p80: value?.p80 ?? null, p90: value?.p90 ?? null }]; })) }; });
  const championIds = new Set(champions.filter((value) => value.backtest_run_id === runValue && (!item || value.item_id === item)).map((value) => value.champion_model_id));
  const exportCsv = () => { const header = 'SKU,Model Name,Model ID,WAPE,MAPE,Bias,RMSE,MAE,Rank,Status,Reason'; const body = rows.map((value) => [value.itemId, value.modelName, value.modelId, value.wape, value.mape, value.bias, value.rmse, value.mae, value.rank, value.calculationStatus, value.reasonCode ?? ''].map((cell) => `"${String(cell ?? '').replaceAll('"', '""')}"`).join(',')); const blob = new Blob([`\uFEFF${[header, ...body].join('\n')}`], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'model-performance.csv'; link.click(); URL.revokeObjectURL(url); };
  const columns: Column<BacktestPerformance>[] = [{ key: 'itemId', label: 'SKU' }, { key: 'modelName', label: 'Model Name', render: (value) => <span>{value.modelName}<small className="muted"> ({value.modelId})</small></span> }, { key: 'wape', label: 'WAPE', align: 'right', render: (value) => value.wape === null ? <EmptyValue reasonCode={value.reasonCode ?? undefined} /> : `${(value.wape * 100).toFixed(1)}%` }, { key: 'mape', label: 'MAPE', align: 'right', render: (value) => value.mape === null ? <EmptyValue reasonCode={value.reasonCode ?? undefined} /> : `${(value.mape * 100).toFixed(1)}%` }, { key: 'bias', label: 'Bias', align: 'right', render: (value) => value.bias === null ? <EmptyValue reasonCode={value.reasonCode ?? undefined} /> : value.bias.toFixed(2) }, { key: 'rmse', label: 'RMSE', align: 'right', render: (value) => value.rmse === null ? <EmptyValue reasonCode={value.reasonCode ?? undefined} /> : value.rmse.toFixed(2) }, { key: 'mae', label: 'MAE', align: 'right', render: (value) => value.mae === null ? <EmptyValue reasonCode={value.reasonCode ?? undefined} /> : value.mae.toFixed(2) }, { key: 'rank', label: 'Rank', align: 'right', render: (value) => value.rank ?? <EmptyValue reasonCode={value.reasonCode ?? undefined} /> }, { key: 'champion', label: 'Champion', render: (value) => championIds.has(value.modelId) ? <span className="tag green">Champion</span> : '—' }];
  return <><div className="comparison-toolbar"><label>Forecast/Backtest Run <select className="table-select" value={runValue} onChange={(event) => setRun(event.target.value)}>{runs.map((value) => <option key={value.backtest_run_id} value={value.backtest_run_id}>{value.forecast_run_id} ({value.test_start}~{value.test_end})</option>)}</select></label><label>SKU <select className="table-select" value={item} onChange={(event) => setItem(event.target.value)}><option value="">전체</option>{items.map((value) => <option key={value}>{value}</option>)}</select></label><label>From <input className="table-select" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>To <input className="table-select" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="button ghost" onClick={exportCsv}>CSV Export</button></div><div className="model-toggle">{models.map((modelId) => <label key={modelId}><input type="checkbox" checked={activeModels.includes(modelId)} onChange={() => setSelected((current) => { const base = current.length ? current : models; return base.includes(modelId) ? base.filter((id) => id !== modelId) : [...base, modelId]; })} /> {modelId}</label>)}</div><ForecastOverlayChart points={points} modelIds={activeModels} validationLabel={runData ? `Validation ${runData.test_start} ~ ${runData.test_end}` : undefined} /><DataTable columns={columns} rows={rows} rowKey={(value) => `${value.backtestRunId}-${value.itemId}-${value.modelId}`} empty="Model Performance가 없습니다." /></>;
}
