'use client';
import { useState } from 'react';
import Button from '@/components/ui/button';
type HistoryItem = { batch_id: string; file_name: string; import_type: string; import_mode: string; total_rows: number; success_rows: number; warning_rows: number; error_rows: number; status: string; rollback_supported: boolean; uploaded_by: string; uploaded_at: string; imported_at: string | null; };
export default function HistoryTable({ initialItems }: { initialItems: HistoryItem[] }) {
  const [items, setItems] = useState(initialItems); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const rollback = async (batchId: string) => { if (!window.confirm('이 batch로 적재된 RAW 행만 rollback합니다. 계속하시겠습니까?')) return; setBusy(batchId); setMessage(null); try { const response = await fetch('/api/admin/imports/rollback', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ batchId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems((rows) => rows.map((row) => row.batch_id === batchId ? { ...row, status: 'ROLLED_BACK' } : row)); } catch (error) { setMessage(error instanceof Error ? error.message : 'rollback에 실패했습니다.'); } finally { setBusy(null); } };
  return <>{message && <p className="text-danger">{message}</p>}<div className="data-table-wrap"><table className="data-table"><thead><tr><th>파일명</th><th>타입</th><th>모드</th><th>총 행</th><th>성공</th><th>경고</th><th>오류</th><th>상태</th><th>사용자</th><th>업로드 시각</th><th>적재 시각</th><th>작업</th></tr></thead><tbody>{items.map((item) => <tr key={item.batch_id}><td>{item.file_name}</td><td>{item.import_type}</td><td>{item.import_mode}</td><td>{item.total_rows}</td><td>{item.success_rows}</td><td>{item.warning_rows}</td><td>{item.error_rows}</td><td>{item.status}</td><td>{item.uploaded_by}</td><td>{item.uploaded_at}</td><td>{item.imported_at || '—'}</td><td>{item.status === 'IMPORTED' && item.rollback_supported ? <Button onClick={() => rollback(item.batch_id)} disabled={busy !== null}>{busy === item.batch_id ? '처리 중…' : 'Rollback'}</Button> : '—'}</td></tr>)}</tbody></table></div></>;
}
