import test from 'node:test';
import assert from 'node:assert/strict';
import { callChatCompletion, type FetchLike } from './llm.ts';

const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const okBody = { choices: [{ message: { role: 'assistant', content: 'ok', tool_calls: [{ id: 'call_1', type: 'function', function: { name: 'getShipmentTrend', arguments: '{"itemCode":"X"}' } }] } }] };

test('환경변수가 없으면 네트워크 호출 없이 error를 반환한다', async () => { const result = await callChatCompletion({ messages: [{ role: 'user', content: 'hello' }] }, async () => { throw new Error('호출되면 안 됨'); }, { env: {} }); assert.match(result.error ?? '', /OPENAI_BASE_URL|OPENAI_API_KEY|OPENAI_MODEL/); });
test('Chat Completions의 tool_calls를 명확한 결과로 파싱한다', async () => { const fetcher: FetchLike = async () => response(okBody); const result = await callChatCompletion({ messages: [{ role: 'user', content: 'hello' }] }, fetcher, { env: { OPENAI_BASE_URL: ' https://example.test/v1 ', OPENAI_API_KEY: ' key ', OPENAI_MODEL: ' model ' } }); assert.equal(result.error, null); assert.equal(result.content, 'ok'); assert.equal(result.toolCalls[0]?.function.name, 'getShipmentTrend'); });
test('json_schema 400은 같은 모델에서 json_object로 한 번만 재시도한다', async () => { const bodies: Record<string, unknown>[] = []; const fetcher: FetchLike = async (_input, init) => { bodies.push(JSON.parse(String(init?.body))); return bodies.length === 1 ? response({ error: { message: 'json_schema unsupported' } }, 400) : response(okBody); }; const result = await callChatCompletion({ messages: [{ role: 'user', content: 'hello' }], response_format: { type: 'json_schema', json_schema: { name: 'x', strict: true, schema: {} } } }, fetcher, { env: { OPENAI_BASE_URL: 'https://fallback-schema.test/v1', OPENAI_API_KEY: 'key', OPENAI_MODEL: 'schema-model' } }); assert.equal(result.error, null); assert.equal(bodies.length, 2); assert.deepEqual(bodies[1].response_format, { type: 'json_object' }); });
test('temperature 오류는 temperature를 제거하고 같은 모델에서 한 번만 재시도한다', async () => { const bodies: Record<string, unknown>[] = []; const fetcher: FetchLike = async (_input, init) => { bodies.push(JSON.parse(String(init?.body))); return bodies.length === 1 ? response({ error: { message: "'temperature' does not support 0 with this model" } }, 400) : response(okBody); }; const result = await callChatCompletion({ messages: [{ role: 'user', content: 'hello' }], temperature: 0 }, fetcher, { env: { OPENAI_BASE_URL: 'https://fallback-temperature.test/v1', OPENAI_API_KEY: 'key', OPENAI_MODEL: 'temperature-model' } }); assert.equal(result.error, null); assert.equal(bodies.length, 2); assert.equal('temperature' in bodies[1], false); });
test('timeout은 주입된 fetch를 abort하고 error로 반환한다', async () => { const fetcher: FetchLike = async (_input, init) => await new Promise<Response>((_resolve, reject) => { init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError'))); }); const result = await callChatCompletion({ messages: [{ role: 'user', content: 'hello' }] }, fetcher, { timeoutMs: 1, env: { OPENAI_BASE_URL: 'https://timeout.test/v1', OPENAI_API_KEY: 'key', OPENAI_MODEL: 'timeout-model' } }); assert.match(result.error ?? '', /timeout|시간/i); });
