import assert from 'node:assert/strict';
import test from 'node:test';
import { agentAnswerResponseFormat, type AgentAnswer } from './schema.ts';
import { type AgentTool, type ToolResult } from './tools.ts';
import { type ChatRequest, type ChatResult } from './llm.ts';
import { runAgent, type AgentLlm } from './orchestrator.ts';

const answer: AgentAnswer = { answer: '완료', verdict: 'SUPPORTED', evidence: [], data_as_of: null, risk: 'LOW', recommended_action: null, cannot_answer: false, cannot_answer_reason: null };
function llmSequence(results: ChatResult[], requests: ChatRequest[]): AgentLlm { let index = 0; return async (request) => { requests.push({ ...request, messages: request.messages.map((message) => ({ ...message, ...(message.tool_calls ? { tool_calls: message.tool_calls.map((call) => ({ ...call, function: { ...call.function } })) } : {}) })) }); return results[index++] ?? { message: null, content: JSON.stringify(answer), toolCalls: [], error: null }; }; }
function tool(name: string, run: (params: Record<string, unknown>) => Promise<ToolResult>, roles: ('USER' | 'ADMIN')[] = ['USER']): AgentTool { return { name, description: '테스트 도구', roles, parameters: { type: 'object', additionalProperties: false, properties: { itemCode: { type: 'string' } }, required: ['itemCode'] }, run }; }
function result(content: string, toolCalls: ChatResult['toolCalls'] = []): ChatResult { return { message: { role: 'assistant', content, ...(toolCalls.length ? { tool_calls: toolCalls } : {}) }, content, toolCalls, error: null }; }
const makeAnswer = (changes: Partial<AgentAnswer>): AgentAnswer => ({ ...answer, ...changes });
const call = (id: string, name: string, args: string) => ({ id, type: 'function' as const, function: { name, arguments: args } });

test('User → LLM → Tool → tool 결과 → LLM 순서로 실행한다', async () => { const requests: ChatRequest[] = []; const requestsResults: ChatResult[] = [result('', [call('call-1', 'lookup', '{"itemCode":"A"}')]), result(JSON.stringify(answer))]; const seen: Record<string, unknown>[] = []; const output = await runAgent({ question: 'A를 찾아줘', user: 'USER', history: [] }, { llm: llmSequence(requestsResults, requests), tools: [tool('lookup', async (params) => { seen.push(params); return { ok: true, data: { value: 1 }, numbers: { value: 1 }, dataAsOf: null, reason: null }; })] }); assert.equal(output.answer, '완료'); assert.deepEqual(seen, [{ itemCode: 'A' }]); assert.equal(requests.length, 2); assert.deepEqual(requests[0].messages.map((message) => message.role), ['user']); assert.deepEqual(requests[1].messages.map((message) => message.role), ['user', 'assistant', 'tool']); assert.equal(requests[1].messages[2].tool_call_id, 'call-1'); assert.equal(output.trace[0]?.name, 'lookup'); assert.deepEqual(requests[0].response_format, agentAnswerResponseFormat); assert.deepEqual(requests[1].response_format, { type: 'json_object' }); });

test('미허용 Tool은 실행하지 않고 cannotAnswer로 끝낸다', async () => { let executed = false; const output = await runAgent({ question: '관리 기능', user: 'USER', history: [] }, { llm: async () => result('', [call('call-1', 'adminOnly', '{}')]), tools: [tool('adminOnly', async () => { executed = true; return { ok: true, data: null, numbers: {}, dataAsOf: null, reason: null }; }, ['ADMIN'])] }); assert.equal(executed, false); assert.equal(output.cannot_answer, true); assert.equal(output.cannot_answer_reason, 'TOOL_NOT_ALLOWED'); assert.equal(output.trace[0]?.reason, 'TOOL_NOT_ALLOWED'); });

test('잘못된 Tool arguments는 실행하지 않고 cannotAnswer로 끝낸다', async () => { let executed = false; const output = await runAgent({ question: '조회', user: 'USER', history: [] }, { llm: async () => result('', [call('call-1', 'lookup', 'not-json')]), tools: [tool('lookup', async () => { executed = true; return { ok: true, data: null, numbers: {}, dataAsOf: null, reason: null }; })] }); assert.equal(executed, false); assert.equal(output.cannot_answer_reason, 'INVALID_TOOL_ARGUMENTS'); assert.equal(output.trace[0]?.reason, 'INVALID_TOOL_ARGUMENTS'); });

test('Tool loop는 최대 6회로 제한한다', async () => { let calls = 0; const requests: ChatRequest[] = []; const repeated = Array.from({ length: 8 }, (_, i) => result('', [call(`call-${i}`, 'lookup', '{"itemCode":"A"}') ])); const output = await runAgent({ question: '계속 조회', user: 'USER', history: [] }, { llm: llmSequence(repeated, requests), tools: [tool('lookup', async () => { calls += 1; return { ok: true, data: {}, numbers: {}, dataAsOf: null, reason: null }; })] }); assert.equal(calls, 6); assert.equal(output.cannot_answer_reason, 'TOOL_LOOP_LIMIT'); assert.equal(requests.length, 6); });

test('답변 숫자가 허용 숫자와 불일치하면 한 번 재생성한다', async () => { let calls = 0; const output = await runAgent({ question: '수량은?', user: 'USER', history: [] }, { llm: async () => { calls += 1; if (calls === 1) return result('', [call('call-1', 'lookup', '{"itemCode":"A"}')]); return result(JSON.stringify(makeAnswer({ answer: calls === 2 ? '수량은 780입니다.' : '수량은 779입니다.' }))); }, tools: [tool('lookup', async () => ({ ok: true, data: { recent_qty: 779 }, numbers: { recent_qty: 779 }, dataAsOf: null, reason: null }))] }); assert.equal(calls, 3); assert.equal(output.answer, '수량은 779입니다.'); });

test('재생성 후에도 숫자가 불일치하면 답변을 폐기한다', async () => { let calls = 0; const output = await runAgent({ question: '수량은?', user: 'USER', history: [] }, { llm: async () => { calls += 1; return result(JSON.stringify(makeAnswer({ answer: '출고량은 999입니다.' }))); }, tools: [] }); assert.equal(calls, 2); assert.equal(output.cannot_answer, true); assert.equal(output.cannot_answer_reason, 'UNSUPPORTED_NUMERIC_CLAIM'); });

