export type ToolRole = 'USER' | 'ADMIN';
export type ToolResult = { ok: boolean; data: unknown; numbers: Record<string, number | null>; dataAsOf: string | null; reason: string | null };
type JsonSchema = { type: 'object'; additionalProperties: false; properties: Record<string, { type: string | string[] }>; required: string[] };
export type AgentTool = { name: string; description: string; parameters: JsonSchema; roles: ToolRole[]; run: (params: Record<string, unknown>) => Promise<ToolResult> };

const itemParameters: JsonSchema = { type: 'object', additionalProperties: false, properties: { itemCode: { type: 'string' } }, required: ['itemCode'] };
const modelParameters: JsonSchema = { type: 'object', additionalProperties: false, properties: { modelBase: { type: 'string' } }, required: ['modelBase'] };
const accuracyParameters: JsonSchema = { type: 'object', additionalProperties: false, properties: { modelBase: { type: 'string' }, fy: { type: ['string', 'null'] } }, required: ['modelBase', 'fy'] };
const roles: ToolRole[] = ['USER', 'ADMIN'];

export function emptyToolResult(reason: string): ToolResult { return { ok: false, data: null, numbers: {}, dataAsOf: null, reason }; }
function parameter(params: Record<string, unknown>, key: string): string | null { const value = params[key]; return typeof value === 'string' && value.trim() ? value.trim() : null; }
function collectNumbers(value: unknown, path = '', output: Record<string, number | null> = {}): Record<string, number | null> { if (Array.isArray(value)) { value.forEach((entry, index) => collectNumbers(entry, `${path}[${index}]`, output)); return output; } if (value && typeof value === 'object') { Object.entries(value).forEach(([key, entry]) => collectNumbers(entry, path ? `${path}.${key}` : key, output)); return output; } if (typeof value === 'number' || value === null) { if (path) output[path] = value; } return output; }
function dataAsOf(value: unknown): string | null { if (Array.isArray(value)) return value.map(dataAsOf).find((entry): entry is string => Boolean(entry)) ?? null; if (!value || typeof value !== 'object') return null; const row = value as Record<string, unknown>; for (const key of ['data_as_of', 'dataAsOf', 'period', 'recent_period', 'latest_period']) if (typeof row[key] === 'string') return row[key]; return null; }
function resultFromData(data: unknown, error: string | null): ToolResult { if (error) return emptyToolResult(error); const isEmpty = data === null || data === undefined || (Array.isArray(data) && data.length === 0); if (isEmpty) return emptyToolResult('ITEM_NOT_FOUND'); return { ok: true, data, numbers: collectNumbers(data), dataAsOf: dataAsOf(data), reason: null }; }

export const agentTools: AgentTool[] = [
  { name: 'getShipmentTrend', description: '품목의 월별 출고량과 3개월·6개월·12개월 평균, 관측 개월 수와 최근 출고를 조회합니다.', parameters: itemParameters, roles, run: async (params) => { const itemCode = parameter(params, 'itemCode'); if (!itemCode) return emptyToolResult('INVALID_ITEM_CODE'); const { getShipmentTrend } = await import('../scm.ts'); const result = await getShipmentTrend(itemCode); return resultFromData(result.rows, result.error); } },
  { name: 'getDemandProfile', description: '품목의 희소 출고 이력에서 ADI, CV², zero-demand rate와 수요유형을 조회합니다.', parameters: itemParameters, roles, run: async (params) => { const itemCode = parameter(params, 'itemCode'); if (!itemCode) return emptyToolResult('INVALID_ITEM_CODE'); const { getDemandProfile } = await import('../scm.ts'); const result = await getDemandProfile(itemCode); return resultFromData(result.rows, result.error); } },
  { name: 'getOlAccuracy', description: '기종의 Sales OL과 SCM OL 정확도인 WAPE와 Bias를 조회합니다. Bias 양수는 과대예측입니다.', parameters: accuracyParameters, roles, run: async (params) => { const modelBase = parameter(params, 'modelBase'); const fy = params.fy === null ? undefined : parameter(params, 'fy'); if (!modelBase) return emptyToolResult('INVALID_MODEL_BASE'); const { getOlAccuracy } = await import('../scm.ts'); const result = await getOlAccuracy(modelBase, fy ?? undefined); return resultFromData({ rows: result.rows, fyRows: result.fyRows }, result.error); } },
  { name: 'getBomRequirement', description: '기종의 CAP 부번, 필수 옵션, SCC·Label, 구성 품목·수량과 공용 품목 여부를 조회합니다.', parameters: modelParameters, roles, run: async (params) => { const modelBase = parameter(params, 'modelBase'); if (!modelBase) return emptyToolResult('INVALID_MODEL_BASE'); const { getBomRequirement } = await import('../scm.ts'); const result = await getBomRequirement(modelBase); return resultFromData(result.rows, result.error); } },
];
